services:
  matomo:
    image: matomo:latest
    platform: linux/arm64
    ports:
      - "8080:80"
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=password
      - MATOMO_DATABASE_DBNAME=matomo
    volumes:
      - matomo:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    platform: linux/arm64
    command: --max-allowed-packet=64MB
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password_here
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql

volumes:
  matomo:
  db: