export const countries = [
  {
    name_en: "Afghanistan",
    name_hr: "Afganistan",
    dial_code: "+93",
    code: "AF",
  },
  {
    name_en: "Aland Islands",
    name_hr: "Ålandski otoci",
    dial_code: "+358",
    code: "AX",
  },
  {
    name_en: "Albania",
    name_hr: "Albanija",
    dial_code: "+355",
    code: "AL",
  },
  {
    name_en: "Algeria",
    name_hr: "Alžir",
    dial_code: "+213",
    code: "DZ",
  },
  {
    name_en: "AmericanSamoa",
    name_hr: "Američka Samoa",
    dial_code: "+1684",
    code: "AS",
  },
  {
    name_en: "Andorra",
    name_hr: "Andora",
    dial_code: "+376",
    code: "AD",
  },
  {
    name_en: "Angola",
    name_hr: "Angola",
    dial_code: "+244",
    code: "AO",
  },
  {
    name_en: "Anguilla",
    name_hr: "Angvila",
    dial_code: "+1264",
    code: "AI",
  },
  {
    name_en: "Antarctica",
    name_hr: "Antarktika",
    dial_code: "+672",
    code: "AQ",
  },
  {
    name_en: "Antigua and Barbuda",
    name_hr: "Antigva i Barbuda",
    dial_code: "+1268",
    code: "AG",
  },
  {
    name_en: "Argentina",
    name_hr: "Argentina",
    dial_code: "+54",
    code: "AR",
  },
  {
    name_en: "Armenia",
    name_hr: "Armenija",
    dial_code: "+374",
    code: "AM",
  },
  {
    name_en: "Aruba",
    name_hr: "Aruba",
    dial_code: "+297",
    code: "AW",
  },
  {
    name_en: "Australia",
    name_hr: "Australija",
    dial_code: "+61",
    code: "AU",
  },
  {
    name_en: "Austria",
    name_hr: "Austrija",
    dial_code: "+43",
    code: "AT",
  },
  {
    name_en: "Azerbaijan",
    name_hr: "Azerbajdžan",
    dial_code: "+994",
    code: "AZ",
  },
  {
    name_en: "Bahamas",
    name_hr: "Bahami",
    dial_code: "+1242",
    code: "BS",
  },
  {
    name_en: "Bahrain",
    name_hr: "Bahrein",
    dial_code: "+973",
    code: "BH",
  },
  {
    name_en: "Bangladesh",
    name_hr: "Bangladeš",
    dial_code: "+880",
    code: "BD",
  },
  {
    name_en: "Barbados",
    name_hr: "Barbados",
    dial_code: "+1246",
    code: "BB",
  },
  {
    name_en: "Belarus",
    name_hr: "Bjelorusija",
    dial_code: "+375",
    code: "BY",
  },
  {
    name_en: "Belgium",
    name_hr: "Belgija",
    dial_code: "+32",
    code: "BE",
  },
  {
    name_en: "Belize",
    name_hr: "Belize",
    dial_code: "+501",
    code: "BZ",
  },
  {
    name_en: "Benin",
    name_hr: "Benin",
    dial_code: "+229",
    code: "BJ",
  },
  {
    name_en: "Bermuda",
    name_hr: "Bermuda",
    dial_code: "+1441",
    code: "BM",
  },
  {
    name_en: "Bhutan",
    name_hr: "Butan",
    dial_code: "+975",
    code: "BT",
  },
  {
    name_en: "Bolivia, Plurinational State of",
    name_hr: "Bolivija",
    dial_code: "+591",
    code: "BO",
  },
  {
    name_en: "Bosnia and Herzegovina",
    name_hr: "Bosna i Hercegovina",
    dial_code: "+387",
    code: "BA",
  },
  {
    name_en: "Botswana",
    name_hr: "Bocvana",
    dial_code: "+267",
    code: "BW",
  },
  {
    name_en: "Brazil",
    name_hr: "Brazil",
    dial_code: "+55",
    code: "BR",
  },
  {
    name_en: "British Indian Ocean Territory",
    name_hr: "Britanski Indijskooceanski teritorij",
    dial_code: "+246",
    code: "IO",
  },
  {
    name_en: "Brunei Darussalam",
    name_hr: "Brunej",
    dial_code: "+673",
    code: "BN",
  },
  {
    name_en: "Bulgaria",
    name_hr: "Bugarska",
    dial_code: "+359",
    code: "BG",
  },
  {
    name_en: "Burkina Faso",
    name_hr: "Burkina Faso",
    dial_code: "+226",
    code: "BF",
  },
  {
    name_en: "Burundi",
    name_hr: "Burundi",
    dial_code: "+257",
    code: "BI",
  },
  {
    name_en: "Cambodia",
    name_hr: "Kambodža",
    dial_code: "+855",
    code: "KH",
  },
  {
    name_en: "Cameroon",
    name_hr: "Kamerun",
    dial_code: "+237",
    code: "CM",
  },
  {
    name_en: "Canada",
    name_hr: "Kanada",
    dial_code: "+1",
    code: "CA",
  },
  {
    name_en: "Cape Verde",
    name_hr: "Zelenortska Republika",
    dial_code: "+238",
    code: "CV",
  },
  {
    name_en: "Cayman Islands",
    name_hr: "Kajmanski otoci",
    dial_code: "+ 345",
    code: "KY",
  },
  {
    name_en: "Central African Republic",
    name_hr: "Srednjoafrička Republika",
    dial_code: "+236",
    code: "CF",
  },
  {
    name_en: "Chad",
    name_hr: "Čad",
    dial_code: "+235",
    code: "TD",
  },
  {
    name_en: "Chile",
    name_hr: "Čile",
    dial_code: "+56",
    code: "CL",
  },
  {
    name_en: "China",
    name_hr: "Kina",
    dial_code: "+86",
    code: "CN",
  },
  {
    name_en: "Christmas Island",
    name_hr: "Božićni otok",
    dial_code: "+61",
    code: "CX",
  },
  {
    name_en: "Cocos (Keeling) Islands",
    name_hr: "Kokosovi otoci",
    dial_code: "+61",
    code: "CC",
  },
  {
    name_en: "Colombia",
    name_hr: "Kolumbija",
    dial_code: "+57",
    code: "CO",
  },
  {
    name_en: "Comoros",
    name_hr: "Komori",
    dial_code: "+269",
    code: "KM",
  },
  {
    name_en: "Congo",
    name_hr: "Kongo",
    dial_code: "+242",
    code: "CG",
  },
  {
    name_en: "Congo, The Democratic Republic of the Congo",
    name_hr: "Demokratska Republika Kongo",
    dial_code: "+243",
    code: "CD",
  },
  {
    name_en: "Cook Islands",
    name_hr: "Cookovi otoci",
    dial_code: "+682",
    code: "CK",
  },
  {
    name_en: "Costa Rica",
    name_hr: "Kostarika",
    dial_code: "+506",
    code: "CR",
  },
  {
    name_en: "Cote d'Ivoire",
    name_hr: "Obala Bjelokosti",
    dial_code: "+225",
    code: "CI",
  },
  {
    name_en: "Croatia",
    name_hr: "Hrvatska",
    dial_code: "+385",
    code: "HR",
  },
  {
    name_en: "Cuba",
    name_hr: "Kuba",
    dial_code: "+53",
    code: "CU",
  },
  {
    name_en: "Cyprus",
    name_hr: "Cipar",
    dial_code: "+357",
    code: "CY",
  },
  {
    name_en: "Czech Republic",
    name_hr: "Češka",
    dial_code: "+420",
    code: "CZ",
  },
  {
    name_en: "Denmark",
    name_hr: "Danska",
    dial_code: "+45",
    code: "DK",
  },
  {
    name_en: "Djibouti",
    name_hr: "Džibuti",
    dial_code: "+253",
    code: "DJ",
  },
  {
    name_en: "Dominica",
    name_hr: "Dominika",
    dial_code: "+1767",
    code: "DM",
  },
  {
    name_en: "Dominican Republic",
    name_hr: "Dominikanska Republika",
    dial_code: "+1849",
    code: "DO",
  },
  {
    name_en: "Ecuador",
    name_hr: "Ekvador",
    dial_code: "+593",
    code: "EC",
  },
  {
    name_en: "Egypt",
    name_hr: "Egipat",
    dial_code: "+20",
    code: "EG",
  },
  {
    name_en: "El Salvador",
    name_hr: "Salvador",
    dial_code: "+503",
    code: "SV",
  },
  {
    name_en: "Equatorial Guinea",
    name_hr: "Ekvatorska Gvineja",
    dial_code: "+240",
    code: "GQ",
  },
  {
    name_en: "Eritrea",
    name_hr: "Eritreja",
    dial_code: "+291",
    code: "ER",
  },
  {
    name_en: "Estonia",
    name_hr: "Estonija",
    dial_code: "+372",
    code: "EE",
  },
  {
    name_en: "Ethiopia",
    name_hr: "Etiopija",
    dial_code: "+251",
    code: "ET",
  },
  {
    name_en: "Falkland Islands (Malvinas)",
    name_hr: "Falklandski otoci",
    dial_code: "+500",
    code: "FK",
  },
  {
    name_en: "Faroe Islands",
    name_hr: "Farski otoci",
    dial_code: "+298",
    code: "FO",
  },
  {
    name_en: "Fiji",
    name_hr: "Fidži",
    dial_code: "+679",
    code: "FJ",
  },
  {
    name_en: "Finland",
    name_hr: "Finska",
    dial_code: "+358",
    code: "FI",
  },
  {
    name_en: "France",
    name_hr: "Francuska",
    dial_code: "+33",
    code: "FR",
  },
  {
    name_en: "French Guiana",
    name_hr: "Francuska Gvajana",
    dial_code: "+594",
    code: "GF",
  },
  {
    name_en: "French Polynesia",
    name_hr: "Francuska Polinezija",
    dial_code: "+689",
    code: "PF",
  },
  {
    name_en: "Gabon",
    name_hr: "Gabon",
    dial_code: "+241",
    code: "GA",
  },
  {
    name_en: "Gambia",
    name_hr: "Gambija",
    dial_code: "+220",
    code: "GM",
  },
  {
    name_en: "Georgia",
    name_hr: "Gruzija",
    dial_code: "+995",
    code: "GE",
  },
  {
    name_en: "Germany",
    name_hr: "Njemačka",
    dial_code: "+49",
    code: "DE",
  },
  {
    name_en: "Ghana",
    name_hr: "Gana",
    dial_code: "+233",
    code: "GH",
  },
  {
    name_en: "Gibraltar",
    name_hr: "Gibraltar",
    dial_code: "+350",
    code: "GI",
  },
  {
    name_en: "Greece",
    name_hr: "Grčka",
    dial_code: "+30",
    code: "GR",
  },
  {
    name_en: "Greenland",
    name_hr: "Grenland",
    dial_code: "+299",
    code: "GL",
  },
  {
    name_en: "Grenada",
    name_hr: "Grenada",
    dial_code: "+1473",
    code: "GD",
  },
  {
    name_en: "Guadeloupe",
    name_hr: "Gvadalupa",
    dial_code: "+590",
    code: "GP",
  },
  {
    name_en: "Guam",
    name_hr: "Guam",
    dial_code: "+1671",
    code: "GU",
  },
  {
    name_en: "Guatemala",
    name_hr: "Gvatemala",
    dial_code: "+502",
    code: "GT",
  },
  {
    name_en: "Guernsey",
    name_hr: "Guernsey",
    dial_code: "+44",
    code: "GG",
  },
  {
    name_en: "Guinea",
    name_hr: "Gvineja",
    dial_code: "+224",
    code: "GN",
  },
  {
    name_en: "Guinea-Bissau",
    name_hr: "Gvineja Bisau",
    dial_code: "+245",
    code: "GW",
  },
  {
    name_en: "Guyana",
    name_hr: "Gvajana",
    dial_code: "+595",
    code: "GY",
  },
  {
    name_en: "Haiti",
    name_hr: "Haiti",
    dial_code: "+509",
    code: "HT",
  },
  {
    name_en: "Holy See (Vatican City State)",
    name_hr: "Vatikan",
    dial_code: "+379",
    code: "VA",
  },
  {
    name_en: "Honduras",
    name_hr: "Honduras",
    dial_code: "+504",
    code: "HN",
  },
  {
    name_en: "Hong Kong",
    name_hr: "Hong Kong",
    dial_code: "+852",
    code: "HK",
  },
  {
    name_en: "Hungary",
    name_hr: "Mađarska",
    dial_code: "+36",
    code: "HU",
  },
  {
    name_en: "Iceland",
    name_hr: "Island",
    dial_code: "+354",
    code: "IS",
  },
  {
    name_en: "India",
    name_hr: "Indija",
    dial_code: "+91",
    code: "IN",
  },
  {
    name_en: "Indonesia",
    name_hr: "Indonezija",
    dial_code: "+62",
    code: "ID",
  },
  {
    name_en: "Iran, Islamic Republic of Persian Gulf",
    name_hr: "Iran",
    dial_code: "+98",
    code: "IR",
  },
  {
    name_en: "Iraq",
    name_hr: "Irak",
    dial_code: "+964",
    code: "IQ",
  },
  {
    name_en: "Ireland",
    name_hr: "Irska",
    dial_code: "+353",
    code: "IE",
  },
  {
    name_en: "Isle of Man",
    name_hr: "Otok Man",
    dial_code: "+44",
    code: "IM",
  },
  {
    name_en: "Israel",
    name_hr: "Izrael",
    dial_code: "+972",
    code: "IL",
  },
  {
    name_en: "Italy",
    name_hr: "Italija",
    dial_code: "+39",
    code: "IT",
  },
  {
    name_en: "Jamaica",
    name_hr: "Jamajka",
    dial_code: "+1876",
    code: "JM",
  },
  {
    name_en: "Japan",
    name_hr: "Japan",
    dial_code: "+81",
    code: "JP",
  },
  {
    name_en: "Jersey",
    name_hr: "Jersey",
    dial_code: "+44",
    code: "JE",
  },
  {
    name_en: "Jordan",
    name_hr: "Jordan",
    dial_code: "+962",
    code: "JO",
  },
  {
    name_en: "Kazakhstan",
    name_hr: "Kazahstan",
    dial_code: "+77",
    code: "KZ",
  },
  {
    name_en: "Kenya",
    name_hr: "Kenija",
    dial_code: "+254",
    code: "KE",
  },
  {
    name_en: "Kiribati",
    name_hr: "Kiribati",
    dial_code: "+686",
    code: "KI",
  },
  {
    name_en: "Korea, Democratic People's Republic of Korea",
    name_hr: "Sjeverna Koreja",
    dial_code: "+850",
    code: "KP",
  },
  {
    name_en: "Korea, Republic of South Korea",
    name_hr: "Južna Koreja",
    dial_code: "+82",
    code: "KR",
  },
  {
    name_en: "Kuwait",
    name_hr: "Kuvajt",
    dial_code: "+965",
    code: "KW",
  },
  {
    name_en: "Kyrgyzstan",
    name_hr: "Kirgistan",
    dial_code: "+996",
    code: "KG",
  },
  {
    name_en: "Laos",
    name_hr: "Laos",
    dial_code: "+856",
    code: "LA",
  },
  {
    name_en: "Latvia",
    name_hr: "Latvija",
    dial_code: "+371",
    code: "LV",
  },
  {
    name_en: "Lebanon",
    name_hr: "Libanon",
    dial_code: "+961",
    code: "LB",
  },
  {
    name_en: "Lesotho",
    name_hr: "Lesoto",
    dial_code: "+266",
    code: "LS",
  },
  {
    name_en: "Liberia",
    name_hr: "Liberija",
    dial_code: "+231",
    code: "LR",
  },
  {
    name_en: "Libyan Arab Jamahiriya",
    name_hr: "Libijska Arapska Džamahirija",
    dial_code: "+218",
    code: "LY",
  },
  {
    name_en: "Liechtenstein",
    name_hr: "Lihtenštajn",
    dial_code: "+423",
    code: "LI",
  },
  {
    name_en: "Lithuania",
    name_hr: "Litva",
    dial_code: "+370",
    code: "LT",
  },
  {
    name_en: "Luxembourg",
    name_hr: "Luksemburg",
    dial_code: "+352",
    code: "LU",
  },
  {
    name_en: "Macao",
    name_hr: "Makao",
    dial_code: "+853",
    code: "MO",
  },
  {
    name_en: "Macedonia",
    name_hr: "Makedonija",
    dial_code: "+389",
    code: "MK",
  },
  {
    name_en: "Madagascar",
    name_hr: "Madagaskar",
    dial_code: "+261",
    code: "MG",
  },
  {
    name_en: "Malawi",
    name_hr: "Malavi",
    dial_code: "+265",
    code: "MW",
  },
  {
    name_en: "Malaysia",
    name_hr: "Malezija",
    dial_code: "+60",
    code: "MY",
  },
  {
    name_en: "Maldives",
    name_hr: "Maldivi",
    dial_code: "+960",
    code: "MV",
  },
  {
    name_en: "Mali",
    name_hr: "Mali",
    dial_code: "+223",
    code: "ML",
  },
  {
    name_en: "Malta",
    name_hr: "Malta",
    dial_code: "+356",
    code: "MT",
  },
  {
    name_en: "Marshall Islands",
    name_hr: "Maršalovi otoci",
    dial_code: "+692",
    code: "MH",
  },
  {
    name_en: "Martinique",
    name_hr: "Martinik",
    dial_code: "+596",
    code: "MQ",
  },
  {
    name_en: "Mauritania",
    name_hr: "Mauritanija",
    dial_code: "+222",
    code: "MR",
  },
  {
    name_en: "Mauritius",
    name_hr: "Mauricijus",
    dial_code: "+230",
    code: "MU",
  },
  {
    name_en: "Mayotte",
    name_hr: "Mayotte",
    dial_code: "+262",
    code: "YT",
  },
  {
    name_en: "Mexico",
    name_hr: "Meksiko",
    dial_code: "+52",
    code: "MX",
  },
  {
    name_en: "Micronesia, Federated States of Micronesia",
    name_hr: "Mikronezija",
    dial_code: "+691",
    code: "FM",
  },
  {
    name_en: "Moldova",
    name_hr: "Moldavija",
    dial_code: "+373",
    code: "MD",
  },
  {
    name_en: "Monaco",
    name_hr: "Monako",
    dial_code: "+377",
    code: "MC",
  },
  {
    name_en: "Mongolia",
    name_hr: "Mongolija",
    dial_code: "+976",
    code: "MN",
  },
  {
    name_en: "Montenegro",
    name_hr: "Crna Gora",
    dial_code: "+382",
    code: "ME",
  },
  {
    name_en: "Montserrat",
    name_hr: "Montserrat",
    dial_code: "+1664",
    code: "MS",
  },
  {
    name_en: "Morocco",
    name_hr: "Maroko",
    dial_code: "+212",
    code: "MA",
  },
  {
    name_en: "Mozambique",
    name_hr: "Mozambik",
    dial_code: "+258",
    code: "MZ",
  },
  {
    name_en: "Myanmar",
    name_hr: "Mjanmar",
    dial_code: "+95",
    code: "MM",
  },
  {
    name_en: "Namibia",
    name_hr: "Namibija",
    dial_code: "+264",
    code: "NA",
  },
  {
    name_en: "Nauru",
    name_hr: "Nauru",
    dial_code: "+674",
    code: "NR",
  },
  {
    name_en: "Nepal",
    name_hr: "Nepal",
    dial_code: "+977",
    code: "NP",
  },
  {
    name_en: "Netherlands",
    name_hr: "Nizozemska",
    dial_code: "+31",
    code: "NL",
  },
  {
    name_en: "Netherlands Antilles",
    name_hr: "Nizozemski Antili",
    dial_code: "+599",
    code: "AN",
  },
  {
    name_en: "New Caledonia",
    name_hr: "Nova Kaledonija",
    dial_code: "+687",
    code: "NC",
  },
  {
    name_en: "New Zealand",
    name_hr: "Novi Zeland",
    dial_code: "+64",
    code: "NZ",
  },
  {
    name_en: "Nicaragua",
    name_hr: "Nikaragva",
    dial_code: "+505",
    code: "NI",
  },
  {
    name_en: "Niger",
    name_hr: "Niger",
    dial_code: "+227",
    code: "NE",
  },
  {
    name_en: "Nigeria",
    name_hr: "Nigerija",
    dial_code: "+234",
    code: "NG",
  },
  {
    name_en: "Niue",
    name_hr: "Niue",
    dial_code: "+683",
    code: "NU",
  },
  {
    name_en: "Norfolk Island",
    name_hr: "Otok Norfolk",
    dial_code: "+672",
    code: "NF",
  },
  {
    name_en: "Northern Mariana Islands",
    name_hr: "Sjevernomarijanski otoci",
    dial_code: "+1670",
    code: "MP",
  },
  {
    name_en: "Norway",
    name_hr: "Norveška",
    dial_code: "+47",
    code: "NO",
  },
  {
    name_en: "Oman",
    name_hr: "Oman",
    dial_code: "+968",
    code: "OM",
  },
  {
    name_en: "Pakistan",
    name_hr: "Pakistan",
    dial_code: "+92",
    code: "PK",
  },
  {
    name_en: "Palau",
    name_hr: "Palau",
    dial_code: "+680",
    code: "PW",
  },
  {
    name_en: "Palestinian Territory, Occupied",
    name_hr: "Palestinsko područje",
    dial_code: "+970",
    code: "PS",
  },
  {
    name_en: "Panama",
    name_hr: "Panama",
    dial_code: "+507",
    code: "PA",
  },
  {
    name_en: "Papua New Guinea",
    name_hr: "Papua Nova Gvineja",
    dial_code: "+675",
    code: "PG",
  },
  {
    name_en: "Paraguay",
    name_hr: "Paragvaj",
    dial_code: "+595",
    code: "PY",
  },
  {
    name_en: "Peru",
    name_hr: "Peru",
    dial_code: "+51",
    code: "PE",
  },
  {
    name_en: "Philippines",
    name_hr: "Filipini",
    dial_code: "+63",
    code: "PH",
  },
  {
    name_en: "Pitcairn",
    name_hr: "Pitcairn",
    dial_code: "+872",
    code: "PN",
  },
  {
    name_en: "Poland",
    name_hr: "Poljska",
    dial_code: "+48",
    code: "PL",
  },
  {
    name_en: "Portugal",
    name_hr: "Portugal",
    dial_code: "+351",
    code: "PT",
  },
  {
    name_en: "Puerto Rico",
    name_hr: "Portoriko",
    dial_code: "+1939",
    code: "PR",
  },
  {
    name_en: "Qatar",
    name_hr: "Katar",
    dial_code: "+974",
    code: "QA",
  },
  {
    name_en: "Romania",
    name_hr: "Rumunjska",
    dial_code: "+40",
    code: "RO",
  },
  {
    name_en: "Russia",
    name_hr: "Rusija",
    dial_code: "+7",
    code: "RU",
  },
  {
    name_en: "Rwanda",
    name_hr: "Ruanda",
    dial_code: "+250",
    code: "RW",
  },
  {
    name_en: "Reunion",
    name_hr: "Reunion",
    dial_code: "+262",
    code: "RE",
  },
  {
    name_en: "Saint Barthelemy",
    name_hr: "Sveti Bartolomej",
    dial_code: "+590",
    code: "BL",
  },
  {
    name_en: "Saint Helena, Ascension and Tristan Da Cunha",
    name_hr: "Sveta Helena",
    dial_code: "+290",
    code: "SH",
  },
  {
    name_en: "Saint Kitts and Nevis",
    name_hr: "Sveti Kristofor i Nevis",
    dial_code: "+1869",
    code: "KN",
  },
  {
    name_en: "Saint Lucia",
    name_hr: "Sveta Lucija",
    dial_code: "+1758",
    code: "LC",
  },
  {
    name_en: "Saint Martin",
    name_hr: "Sveti Martin",
    dial_code: "+590",
    code: "MF",
  },
  {
    name_en: "Saint Pierre and Miquelon",
    name_hr: "Sveti Petar i Mikelon",
    dial_code: "+508",
    code: "PM",
  },
  {
    name_en: "Saint Vincent and the Grenadines",
    name_hr: "Sveti Vincent i Grenadini",
    dial_code: "+1784",
    code: "VC",
  },
  {
    name_en: "Samoa",
    name_hr: "Samoa",
    dial_code: "+685",
    code: "WS",
  },
  {
    name_en: "San Marino",
    name_hr: "San Marino",
    dial_code: "+378",
    code: "SM",
  },
  {
    name_en: "Sao Tome and Principe",
    name_hr: "Sao Tome i Principe",
    dial_code: "+239",
    code: "ST",
  },
  {
    name_en: "Saudi Arabia",
    name_hr: "Saudijska Arabija",
    dial_code: "+966",
    code: "SA",
  },
  {
    name_en: "Senegal",
    name_hr: "Senegal",
    dial_code: "+221",
    code: "SN",
  },
  {
    name_en: "Serbia",
    name_hr: "Srbija",
    dial_code: "+381",
    code: "RS",
  },
  {
    name_en: "Seychelles",
    name_hr: "Sejšeli",
    dial_code: "+248",
    code: "SC",
  },
  {
    name_en: "Sierra Leone",
    name_hr: "Sijera Leone",
    dial_code: "+232",
    code: "SL",
  },
  {
    name_en: "Singapore",
    name_hr: "Singapur",
    dial_code: "+65",
    code: "SG",
  },
  {
    name_en: "Slovakia",
    name_hr: "Slovačka",
    dial_code: "+421",
    code: "SK",
  },
  {
    name_en: "Slovenia",
    name_hr: "Slovenija",
    dial_code: "+386",
    code: "SI",
  },
  {
    name_en: "Solomon Islands",
    name_hr: "Solomonski otoci",
    dial_code: "+677",
    code: "SB",
  },
  {
    name_en: "Somalia",
    name_hr: "Somalija",
    dial_code: "+252",
    code: "SO",
  },
  {
    name_en: "South Africa",
    name_hr: "Južna Afrika",
    dial_code: "+27",
    code: "ZA",
  },
  {
    name_en: "South Sudan",
    name_hr: "Južni Sudan",
    dial_code: "+211",
    code: "SS",
  },
  {
    name_en: "South Georgia and the South Sandwich Islands",
    name_hr: "Južna Georgija i otočje Južni Sandwich",
    dial_code: "+500",
    code: "GS",
  },
  {
    name_en: "Spain",
    name_hr: "Španjolska",
    dial_code: "+34",
    code: "ES",
  },
  {
    name_en: "Sri Lanka",
    name_hr: "Šri Lanka",
    dial_code: "+94",
    code: "LK",
  },
  {
    name_en: "Sudan",
    name_hr: "Sudan",
    dial_code: "+249",
    code: "SD",
  },
  {
    name_en: "Suriname",
    name_hr: "Surinam",
    dial_code: "+597",
    code: "SR",
  },
  {
    name_en: "Svalbard and Jan Mayen",
    name_hr: "Svalbard i Jan Mayen",
    dial_code: "+47",
    code: "SJ",
  },
  {
    name_en: "Swaziland",
    name_hr: "Svazi",
    dial_code: "+268",
    code: "SZ",
  },
  {
    name_en: "Sweden",
    name_hr: "Švedska",
    dial_code: "+46",
    code: "SE",
  },
  {
    name_en: "Switzerland",
    name_hr: "Švicarska",
    dial_code: "+41",
    code: "CH",
  },
  {
    name_en: "Syrian Arab Republic",
    name_hr: "Sirija",
    dial_code: "+963",
    code: "SY",
  },
  {
    name_en: "Taiwan",
    name_hr: "Tajvan",
    dial_code: "+886",
    code: "TW",
  },
  {
    name_en: "Tajikistan",
    name_hr: "Tadžikistan",
    dial_code: "+992",
    code: "TJ",
  },
  {
    name_en: "Tanzania, United Republic of Tanzania",
    name_hr: "Tanzanija",
    dial_code: "+255",
    code: "TZ",
  },
  {
    name_en: "Thailand",
    name_hr: "Tajland",
    dial_code: "+66",
    code: "TH",
  },
  {
    name_en: "Timor-Leste",
    name_hr: "Istočni Timor",
    dial_code: "+670",
    code: "TL",
  },
  {
    name_en: "Togo",
    name_hr: "Togo",
    dial_code: "+228",
    code: "TG",
  },
  {
    name_en: "Tokelau",
    name_hr: "Tokelau",
    dial_code: "+690",
    code: "TK",
  },
  {
    name_en: "Tonga",
    name_hr: "Tonga",
    dial_code: "+676",
    code: "TO",
  },
  {
    name_en: "Trinidad and Tobago",
    name_hr: "Trinidad i Tobago",
    dial_code: "+1868",
    code: "TT",
  },
  {
    name_en: "Tunisia",
    name_hr: "Tunis",
    dial_code: "+216",
    code: "TN",
  },
  {
    name_en: "Turkey",
    name_hr: "Turska",
    dial_code: "+90",
    code: "TR",
  },
  {
    name_en: "Turkmenistan",
    name_hr: "Turkmenistan",
    dial_code: "+993",
    code: "TM",
  },
  {
    name_en: "Turks and Caicos Islands",
    name_hr: "Otoci Turks i Caicos",
    dial_code: "+1649",
    code: "TC",
  },
  {
    name_en: "Tuvalu",
    name_hr: "Tuvalu",
    dial_code: "+688",
    code: "TV",
  },
  {
    name_en: "Uganda",
    name_hr: "Uganda",
    dial_code: "+256",
    code: "UG",
  },
  {
    name_en: "Ukraine",
    name_hr: "Ukrajina",
    dial_code: "+380",
    code: "UA",
  },
  {
    name_en: "United Arab Emirates",
    name_hr: "Ujedinjeni Arapski Emirati",
    dial_code: "+971",
    code: "AE",
  },
  {
    name_en: "United Kingdom",
    name_hr: "Ujedinjeno Kraljevstvo",
    dial_code: "+44",
    code: "GB",
  },
  {
    name_en: "United States",
    name_hr: "Sjedinjene Američke Države",
    dial_code: "+1",
    code: "US",
  },
  {
    name_en: "Uruguay",
    name_hr: "Urugvaj",
    dial_code: "+598",
    code: "UY",
  },
  {
    name_en: "Uzbekistan",
    name_hr: "Uzbekistan",
    dial_code: "+998",
    code: "UZ",
  },
  {
    name_en: "Vanuatu",
    name_hr: "Vanuatu",
    dial_code: "+678",
    code: "VU",
  },
  {
    name_en: "Venezuela, Bolivarian Republic of Venezuela",
    name_hr: "Venezuela",
    dial_code: "+58",
    code: "VE",
  },
  {
    name_en: "Vietnam",
    name_hr: "Vijetnam",
    dial_code: "+84",
    code: "VN",
  },
  {
    name_en: "Virgin Islands, British",
    name_hr: "Britanski Djevičanski otoci",
    dial_code: "+1284",
    code: "VG",
  },
  {
    name_en: "Virgin Islands, U.S.",
    name_hr: "Američki Djevičanski otoci",
    dial_code: "+1340",
    code: "VI",
  },
  {
    name_en: "Wallis and Futuna",
    name_hr: "Wallis i Futuna",
    dial_code: "+681",
    code: "WF",
  },
  {
    name_en: "Yemen",
    name_hr: "Jemen",
    dial_code: "+967",
    code: "YE",
  },
  {
    name_en: "Zambia",
    name_hr: "Zambija",
    dial_code: "+260",
    code: "ZM",
  },
  {
    name_en: "Zimbabwe",
    name_hr: "Zimbabve",
    dial_code: "+263",
    code: "ZW",
  },
];
